-- CREATE DATABASE IF NOT EXIST TaskTracker;

-- USE TaskTracker;

CREATE TABLE IF NOT EXISTS Users(
    UID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    Email TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Tasks(
    TID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    Status TEXT NOT NULL,
    UID INT NOT NULL,
    FOREIGN KEY(UID) REFERENCES Users(UID)
);

SELECT * FROM Users;